### ISSUE TITLE
求大佬帮看看报错原因

### ISSUE THREAD

**Issue by a810291783** [anjia0532/unidbg-boot-server#21]
本地unidbg可以正常运行 ，添加到unidbg-boot-server报错

求大佬帮看看什么原因

2024-06-03 14:17:17.772  WARN 6180 --- [         task-1] com.github.unidbg.AbstractEmulator       : emulate RX@0x4022b1f8[libfekit.so]0x22b1f8 exception sp=unidbg@0xbffff700, msg=java.lang.NullPointerException, offset=873ms
lilac open file:/data/user/999
lilac open file:/data/user/128
lilac open file:/data/user/10
lilac open file:/data/user/11
lilac open file:/data/user/12
lilac open file:/data/user/13
lilac open file:/data/user/14
lilac open file:/data/user/15
lilac open file:/data/user/16
lilac open file:/data/user/17
lilac open file:/data/user/18
lilac open file:/data/user/19
lilac open file:/data/user/20
2024-06-03 14:17:17.889  WARN 6180 --- [         task-1] c.g.unidbg.linux.ARM64SyscallHandler     : fstatat64 dirfd=-100, pathname=E:/data/user/0/com.tencent.mobileqq/files/.android_lq, statbuf=RW@0x40f7c990, flags=0
lilac open file:/system/lib/libhoudini.so
lilac open file:/system/lib64/libhoudini.so
lilac open file:/sdcard/Android/
2024-06-03 14:17:18.016  WARN 6180 --- [         task-1] c.g.unidbg.linux.ARM64SyscallHandler     : handleInterrupt intno=2, NR=113, svcNumber=0x0, PC=RX@0x40bfa86c[libc.so]0x6a86c, LR=RX@0x40bad888[libc.so]0x1d888, syscall=null

java.lang.UnsupportedOperationException: clk_id=3
	at com.github.unidbg.linux.ARM64SyscallHandler.clock_gettime(ARM64SyscallHandler.java:1125)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:311)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.BaseTask.continueRun(BaseTask.java:104)
	at com.github.unidbg.thread.ThreadTask.dispatch(ThreadTask.java:36)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:52)
	at com.anjia.unidbgserver.service.MobileQQService.initUin(MobileQQService.java:113)
	at com.anjia.unidbgserver.service.MobileQQService.init(MobileQQService.java:93)
	at com.anjia.unidbgserver.service.MobileQQService.getXwDebugID(MobileQQService.java:118)
	at com.anjia.unidbgserver.service.MobileQQServiceWorker.doWork(MobileQQServiceWorker.java:85)
	at com.anjia.unidbgserver.service.MobileQQServiceWorker.getXwDebugID(MobileQQServiceWorker.java:78)
	at com.anjia.unidbgserver.service.MobileQQServiceWorker$$FastClassBySpringCGLIB$$2ae6b84c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by anjia0532** [comment]
一个是你看看你的本地跑的unidbg的和boot-server的unidbg是不是一样的版本，你要是本地运行的自己魔改东西了，那肯定不一样。
再一个你如果本地每次new都正常，用unidbg-server不行，那大概率是某些东西不能复用，需要调用几次就得释放掉，重新new。

看你报错信息是空指针异常，你自己调试看看吧
