### ISSUE TITLE
unidbg魔改快照版打包运行出错

### ISSUE THREAD

**Issue by a810291783** [anjia0532/unidbg-boot-server#24]
使用默认9.0.7可以正常运行，但是这个版本不满足项目需求，所以使用魔改的快照版。
电脑做系统之前是正常的，重做个系统后打包运行出错。
麻烦大佬帮忙看看是什么原因。

PS D:\9.0.75\V1.0\unidbg-boot-server-main> java -jar target\unidbg-boot-server-0.0.1-SNAPSHOT.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2024-07-24 14:31:55.783  INFO 6272 --- [           main] c.a.u.UnidbgServerApplication            : Starting UnidbgServerApplication v0.0.1-SNAPSHOT using Java 1.8.0_411 on PC-20240708FXQC with PID 6272 (D:\9.0.75\V1.0\unidbg-boot-server-main\target\unidbg-boot-server-0.0.1-SNAPSHOT.jar started by Administrator in D:\9.0.75\V1.0\unidbg-boot-server-main)
2024-07-24 14:31:55.785  INFO 6272 --- [           main] c.a.u.UnidbgServerApplication            : The following profiles are active: dev
2024-07-24 14:31:56.659  WARN 6272 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreation
Exception: Error creating bean with name 'MobileQQWorker': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.anjia.unidbgserver.service.MobileQQServiceWorker] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@5910e440]
2024-07-24 14:31:56.684 ERROR 6272 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'MobileQQWorker': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.anjia.unidbgserver.service.MobileQQServiceWorker] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@5910e440]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:289)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1302)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1219)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
        at com.anjia.unidbgserver.UnidbgServerApplication.main(UnidbgServerApplication.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.anjia.unidbgserver.service.MobileQQServiceWorker] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@5910e440]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
        at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:267)
        ... 24 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/configurationprocessor/json/JSONException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getDeclaredMethods(Unknown Source)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463)
        ... 26 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.configurationprocessor.json.JSONException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 30 common frames omitted

**Comment by a810291783** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.3</version>
        <relativePath/> 
    </parent>

    <groupId>com.anjia</groupId>
    <artifactId>unidbg-boot-server</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>unidbg-boot-server</name>
    <description>Unidbg Spring Boot Server</description>

    <properties>
        
        <java.version>1.8</java.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <unidbg.version>0.9.8-SNAPSHOT</unidbg.version>
        <commons-lang3.version>3.12.0</commons-lang3.version>
        <commons-io.version>2.11.0</commons-io.version>
        <streamex.version>0.7.3</streamex.version>
        <commons-codec.version>1.15</commons-codec.version>
        <jib-maven-plugin.version>3.1.4</jib-maven-plugin.version>
        
        <maven.test.skip>true</maven.test.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf-spring5</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>${commons-codec.version}</version>
        </dependency>
        <dependency>
            <groupId>one.util</groupId>
            <artifactId>streamex</artifactId>
            <version>${streamex.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang3.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons-io.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.zhkl0228</groupId>
            <artifactId>unidbg-api</artifactId>
            <version>${unidbg.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.zhkl0228</groupId>
            <artifactId>unidbg-android</artifactId>
            <version>${unidbg.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.zhkl0228</groupId>
            <artifactId>unidbg-dynarmic</artifactId>
            <version>${unidbg.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>unidbg-api</artifactId>
                    <groupId>com.github.zhkl0228</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.zhkl0228</groupId>
            <artifactId>unidbg-unicorn2</artifactId>
            <version>${unidbg.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>${jib-maven-plugin.version}</version>
                    <configuration>
                        <from>
                            <image>anjia0532/openjdk-8-alpine-lib:3.2.0</image>
                        </from>
                        <extraDirectories>
                            <paths>
                                <path>src/main/docker/jib</path>
                            </paths>
                        </extraDirectories>
                        <container>
                            <entrypoint>
                                <shell>/sbin/tini</shell>
                                <option>--</option>
                            </entrypoint>
                            <args>
                                <arg>sh</arg>
                                <arg>-c</arg>
                                <arg>chmod +x /entrypoint.sh &amp;&amp; /entrypoint.sh</arg>
                            </args>
                            <ports>
                                <port>9999</port>
                            </ports>
                        </container>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>

**Comment by anjia0532** [comment]
cmd 执行 java -version 看看版本。看看是不是默认装成非jdk8了

**Comment by a810291783** [comment]
> cmd 执行`java -version`看看版本。看看是不是默认装成非jdk8了。 再cmd执行`mvn install`把jar都下载下来 最后执行`java -jar xxx.jar`运行项目

所有操作都没报错，只有运行jar包时报错，按照大佬的方法测试还是同意的错误。  

C:\Users\Administrator>java -version
java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)


PS D:\9.0.75\V1.2\unidbg-boot-server-main> mvn install
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.anjia:unidbg-boot-server >--------------------
[INFO] Building unidbg-boot-server 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.2.0:resources (default-resources) @ unidbg-boot-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 2 resources
[INFO] Copying 4 resources
[INFO]
[INFO] --- compiler:3.8.1:compile (default-compile) @ unidbg-boot-server ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- resources:3.2.0:testResources (default-testResources) @ unidbg-boot-server ---
[INFO] Not copying test resources
[INFO]
[INFO] --- compiler:3.8.1:testCompile (default-testCompile) @ unidbg-boot-server ---
[INFO] Not compiling test sources
[INFO]
[INFO] --- surefire:2.22.2:test (default-test) @ unidbg-boot-server ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- jar:3.2.2:jar (default-jar) @ unidbg-boot-server ---
[INFO] Building jar: D:\9.0.75\V1.2\unidbg-boot-server-main\target\unidbg-boot-server-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- spring-boot:2.6.3:repackage (repackage) @ unidbg-boot-server ---
[INFO]
[INFO] Installing D:\9.0.75\V1.2\unidbg-boot-server-main\target\unidbg-boot-server-0.0.1-SNAPSHOT.jar to F:\IntelliJ IDEA 2024.1.1\plugins\maven\repository\com\anjia\unidbg-boot-server\0.0.1-SNAPSHOT\unidbg-boot-server-0.0.1-SNAPSHOT.jar
[INFO] Installing D:\9.0.75\V1.2\unidbg-boot-server-main\pom.xml to F:\IntelliJ IDEA 2024.1.1\plugins\maven\repository\com\anjia\unidbg-boot-server\0.0.1-SNAPSHOT\unidbg-boot-server-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.763 s
[INFO] Finished at: 2024-07-24T15:53:42+08:00
[INFO] ------------------------------------------------------------------------


PS D:\9.0.75\V1.2\unidbg-boot-server-main> java -jar target\unidbg-boot-server-0.0.1-SNAPSHOT.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2024-07-24 15:54:40.434  INFO 13340 --- [           main] c.a.u.UnidbgServerApplication            : Starting UnidbgServerApplication v0.0.1-SNAPSHOT using Java 1.8.0_411 on PC-20240708FXQC with PID 13340 (D:\9.0.75\V1.2\unidbg-boot-server-main\target\unidbg-boot-server-0.0.1-SNAPSHOT.jar started by Administrator in D:\9.0.75\V1.2\unidbg-boot-server-main)
2024-07-24 15:54:40.437  INFO 13340 --- [           main] c.a.u.UnidbgServerApplication            : The following profiles are active: dev
2024-07-24 15:54:41.312  WARN 13340 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreatio
nException: Error creating bean with name 'mobileQQWorker': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.anjia.unidbgserver.service.MobileQQServiceWorker] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@5910e440]
2024-07-24 15:54:41.336 ERROR 13340 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mobileQQWorker': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.anjia.unidbgserver.service.MobileQQServiceWorker] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@5910e440]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:289)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1302)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1219)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
        at com.anjia.unidbgserver.UnidbgServerApplication.main(UnidbgServerApplication.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.anjia.unidbgserver.service.MobileQQServiceWorker] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@5910e440]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
        at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:267)
        ... 24 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/configurationprocessor/json/JSONException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getDeclaredMethods(Unknown Source)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463)
        ... 26 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.configurationprocessor.json.JSONException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 30 common frames omitted

PS D:\9.0.75\V1.2\unidbg-boot-server-main>

**Comment by anjia0532** [comment]
你百度搜搜 `java.lang.IllegalStateException: Failed to introspect Class` 看看吧。

**Comment by anjia0532** [comment]
你自己魔改的unidbg install 到本地了没？

https://github.com/anjia0532/unidbg-boot-server?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E5%AE%9A%E5%88%B6%E5%8C%96%E5%BF%AB%E7%85%A7%E7%89%88unidbg

**Comment by a810291783** [comment]
> 你自己魔改的unidbg install 到本地了没？
> 
> https://github.com/anjia0532/unidbg-boot-server?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E5%AE%9A%E5%88%B6%E5%8C%96%E5%BF%AB%E7%85%A7%E7%89%88unidbg

嗯在本地了

**Comment by a810291783** [comment]
经过排查找到JSONException异常签名的问题，不知道是和spring boot版本不兼容的原因还是什么其他的原因，小白不太懂，反正总算是找到问题所在了。另外感谢大佬一直在跟进帮助解决问题。

**Comment by anjia0532** [comment]
`Caused by: java.lang.ClassNotFoundException: org.springframework.boot.configurationprocessor.json.JSONException` 看报错是缺库

**Comment by a810291783** [comment]
org.springframework.boot.configurationprocessor.json.JSONException
改为
org.json.JSONException;
org.json.JSONObject;
解决问题。
